// As notas: as listas marcadas com * na página "listas" do Notion
// (fefe.garden › taxonomia), puxadas em 02/10/2026, sem o asterisco.
// https://app.notion.com/p/3b58b41e2db480bba7f7e06cb37e50ef
//
// Uma nota = um título + itens, um por linha, como no bloco de notas.
// `data` (AAAA-MM-DD) é opcional: o Notion não tem data de nenhuma lista, então
// nenhuma tem. Com data, a página ordena da mais nova pra mais velha; sem data,
// vale a ordem daqui, que é a do Notion. O endereço (/notes#…) sai do título.

window.NOTAS = [
  {
    titulo: "coisas infinitas",
    itens: [
      "aquela cutícula levantadinha no meio da reunião",
      "a reunião",
      "minha saudade",
      "a avenida nossa senhora de copacabana",
      "a memória",
      "o ultimo minuto do uber que tá pra chegar",
      "a coletividade",
      "o frio da barriga no tobogã da contorno",
      "a intimidade",
      "o tempo, tempo, tempo, tempo",
      "o geladinho dos azulejos",
      "a pilha de louça",
      "a matemática",
      "a arrogância",
      "a vontade de saber",
      "o último pensamento antes de dormir",
      "coisas que eu quero saber",
      "o livro que você esta lendo",
      "o limite de todas as coisas",
      "das estruturas elementares",
      "daquele dia",
      "coisas que nao tem volta",
      "saber",
      "falar",
      "fazer",
      "coisas imperfeitas",
      "ideias geniais",
      "o amor",
      "cotovelos",
      "y umbigos",
      "y corações (apaixonados)",
      "o pra sempre",
      "círculos",
      "conversas verdadeiramente sinceras",
      "as línguas",
      "pão de fermentação natural",
      "certezas",
      "o homem",
      "o sossego",
      "mudanças",
      "quando a cabeça descola do corpo",
      "o salgado da padaria da esquina",
      "sonhos",
      "objetos feito a mão",
      "a ideia de perfeição.",
      "coisas que cabem na minha cabeça",
      "algumas coisas que existem:",
      "o resto de barulho que fica no ouvido",
      "a beleza",
      "cheesecake de frutas vermelhas",
      "borboletas no estômago",
      "cheiro de casa de vó",
      "pensamentos devolvidos pra cabeça",
      "dias normais",
      "olhos que sorriem",
      "pepitas de espontaneidade",
      "dias incríveis",
      "um lugar dentro de outro lugar",
      "nosso corpo",
      "entorpecentes",
      "átomos",
      "filhotes",
      "o exato segundo que a flor desabrocha",
      "gente que é ímã",
      "palavra com 3 letras y 2 acentos",
      "estados de espírito",
      "algo que ainda não tem nome",
      "coisas que eu não entendo",
      "fogão de indução",
      "quem pede suco de caju",
      "e não gosta de coentro",
      "amor de mãe",
      "a rua do amendoim",
      "o painel de luzes do meu carro",
      "o hype da palavra bowl",
      "quem usa luz fria na própria casa",
      "a estrutura elementar das coisas",
      "nascentes de rio",
      "o rio de janeiro",
      "onde fica mesmo o brasil",
      "aviões",
      "asas em geral",
      "a imaginação e suas capacidades",
      "uns roxos que surgem na minha perna",
      "muitas explicações",
      "semi tons",
      "quando a astrologia faz muito sentido",
      "como as músicas entram nos discos",
      "todo o resto",
      "coisas que cabem na minha cabeça:",
      "quase tudo da lista do mercado",
      "alguns sonhos que ficaram pra depois",
      "y os que ficaram pelo caminho",
      "letras de músicas que eu aprendi errado",
      "datas de aniversário (menos o da Miras)",
      "os signos dos meus amigos",
      "a fórmula de báskara",
      "o que eu deveria ter entregue essa semana",
      "receitas de bolo",
      "neurônios",
      "olhos",
      "meu jeito de ver o mundo"
    ]
  },
  {
    titulo: "habilidades invejáveis",
    itens: [
      "falar português com sotaque brasileiro",
      "falar bem dos outros",
      "falar bem da gente",
      "chorar de verdade (em público ou solo)",
      "riso fácil",
      "puxar orelhas com doçura",
      "retomar a conversa ao ponto exato que ela foi interrompida",
      "assumir uma seriedade emergencial",
      "dizer não sem pestanejar",
      "fazer uma mesa inteira se sentir cumprimentada",
      "resumir histórias",
      "alongar causos",
      "ler pistas de dança",
      "ficar a noite inteira de salto alto",
      "ir embora à francesa",
      "gostar de quem gosta da gente",
      "línguas e instrumentos em geral",
      "gastar com bom gosto",
      "levar desaforo pra casa",
      "ou, digamos assim, escolher as melhores batalhas",
      "deixar as toalhas de banho felpudas",
      "embaixadinha (desculpa, acho lindo)",
      "dormir em qualquer lugar",
      "ficar em silêncio",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "admitir a própria inveja",
      "e dizer sim pro que restar.",
      "coisas que o dinheiro compra",
      "uma viagem de classe executiva",
      "uma coquinha gelada depois do almoço",
      "o almoço"
    ]
  },
  {
    titulo: "coisas de gente corajosa",
    itens: [
      "chegar sozinho em festas na adolescência",
      "mandar oiii (com mais de um i)",
      "tchau também",
      "se cavucar de verdade na terapia",
      "ficar caladinha",
      "conversar sobre sexo ainda vestidos",
      "chegar sozinho em festas de adulto",
      "sair de casa",
      "emprestar livros",
      "olhar fininho pra um desconhecido",
      "e-mails curtos",
      "mensagens longas",
      "ligações telefônicas - chamar e atender",
      "mudar de cidade",
      "y opinião",
      "terças feiras",
      "falar dos próprios limites?",
      "agradecer elogios",
      "criar espaços",
      "olhar pro espelho (ou não)",
      "dizer sim (ou não)",
      "abrir a quarta garrafa de pinot noir",
      "pintar a parede da sala",
      "primeiras y últimas vezes",
      "admitir as penúltimas",
      "esquecer a contabilidade dos afetos",
      "falar até clarear os pensamentos",
      "dirigir com meu pai do lado",
      "“te busco as 19 30!”",
      "tomar mais de três baermates",
      "promessas de mindinho",
      "voltar mais cedo",
      "(…)",
      "preencher uma página em branco"
    ]
  },
  {
    titulo: "coisas que eu já me acostumei:",
    itens: [
      "escovar os dentes",
      "comer coisas que eu não gosto",
      "perguntar a opinião de amigas mulheres",
      "ter um quartinho da bagunça",
      "esconder quase a qualquer custo meu quartinho da bagunça",
      "arrumar a cama",
      "tentar arrumar meu quartinho da bagunça",
      "escrever até completar três páginas",
      "levar um bikini e um moletom pra qualquer viagem",
      "algumas ausencias e presenças",
      "acordar cedinho",
      "pedir ajuda",
      "dias de chuva",
      "digitar sem olhar pro teclado",
      "sentir medo",
      "a ladeira colossal no caminho pra academia",
      "o frizz que meu cabelo dá no rio de janeiro",
      "discordar caladinha",
      "emitir notas fiscais",
      "chamar o chaveiro",
      "resolver na última hora",
      "não fazer a menor ideia",
      "perder meu celular",
      "chorar por qualquer bobagem",
      "lembrar de qualquer bobagem",
      "falarem que eu pareço demais com fulana",
      "fazer florzinhas variadas na tábua de frios",
      "com o fato de que jamais acostumarei com os primeiros km de uma corrida",
      "lidar com a louça enquanto cozinho",
      "meu pé de picolé",
      "nadar",
      "me espantar",
      "y logo acostumar."
    ]
  },
  {
    titulo: "unidades de medida relevantes:",
    itens: [
      "um punhado",
      "voltas ao sol",
      "a vida que cabe em horas de carnaval",
      "noites de sexta",
      "noites de sexta que viram manhãs de domingo",
      "viagens sozinhas",
      "eleições y copas do mundo",
      "uma talagada",
      "quanta desilusão o coração da gente aguenta?",
      "altura de crianças",
      "oceanos",
      "a fragilidade",
      "em quantos apartamentos vou morar até envelhecer?",
      "a ambiguidade dos assentos de sofá",
      "capas de jornal",
      "daqui até ali tem umas 4 drogarias araújo",
      "dois palitos",
      "palmas",
      "dedos",
      "te conheço há quase 1kg de sal.",
      "minutos de microondas",
      "sujeira aceitável no sapato",
      "dores de cabeça",
      "apertos do coração",
      "mordidas na língua",
      "pedaços de pizza y panelas de feijão",
      "mergulhos no mar",
      "8 reais de uber",
      "🤏🏼",
      "tempo longe do celular",
      "legenda: eu quero saber"
    ]
  },
  {
    titulo: "coisas realmente importantes:",
    itens: [
      "saber tentar falar o que tá dentro da gente.",
      "garantir melhorias constantes na minha receita de brigadeiro.",
      "um bom corte de cabelo",
      "e um bom spray anti-frizz.",
      "sair de casa.",
      "sentir tesão.",
      "economizar dinheiro.",
      "ficar em casa.",
      "carnaval.",
      "saber exatamente a música que vai salvar uma noite de um final prematuro.",
      "ou delegar playlists para alguém massa.",
      "olhar profundamente para o mundo mas saber ignorar algumas coisas.",
      "andar de mãos dadas.",
      "ser o contato de emergência de alguém.",
      "reinventar minhas amizades.",
      "não enrijecer.",
      "frutas frescas.",
      "fazer o que eu quero",
      "e o que eu devo.",
      "um powerbank compacto e carregado.",
      "conseguir/ousar/tentar perdoar.",
      "dormir bem.",
      "lembrar de alguns sonhos.",
      "ligar pro meu pai.",
      "cultivar espaços vazios e preenchê-los com sabedoria.",
      "me sentir gata de vez em quando.",
      "deixar o celular pra fora do quarto.",
      "pedir desculpas.",
      "manter o hábito de só viajar com mala de mão.",
      "dar algum peso às pequenas decisões e atribuir leveza aos fatídicos dias.",
      "acertar quando der.",
      "me",
      "reavaliar as importâncias;",
      "isso e não esquecer de tirar férias. feliz aniversário pra mim :)"
    ]
  },
  {
    titulo: "coisas que eu gosto:",
    itens: [
      "ver gente descolada sendo romântica",
      "um pessoal da minha família",
      "dormir cedo",
      "coca zero",
      "a música palco do Gil",
      "toda música do Gil",
      "vestir amigas com minhas roupas",
      "qualquer coisa que o Gil faz",
      "lençol que acabou de trocar",
      "tomar um porre de vinho",
      "sair e não beber",
      "organizar meu guarda roupa",
      "fingir que gosto de café sem açúcar",
      "passar maquiagem e ficar em casa",
      "pintar as unhas do pé de preto",
      "acordar antes do despertador",
      "versões acústicas",
      "brócolis tostado com 10kg de alho",
      "o rio de janeiro",
      "quando alguém canta no chuveiro sem saber que eu to ouvindo cantar",
      "silêncios confortáveis",
      "overdressing",
      "reclamar",
      "feira de rua",
      "a língua portuguesa com sotaque do Brasil",
      "passear de mão dada",
      "quando a ligação não é telemarketing",
      "falar mal de gente chata",
      "fazer listas"
    ]
  },
  {
    titulo: "medidas emergenciais para um cotidiano feroz:",
    itens: [
      "sair do quarto",
      "alguma dose de qualquer exagero",
      "preencher silêncios",
      "dormir com a janela aberta",
      "virar a esquina sem dar a seta",
      "cortar o cabelo",
      "elaborar playlists para ocasiões utópicas",
      "comprar uma passagem pra depois de amanhã",
      "comprar uma passagem para ano que vem",
      "apertar os cintos",
      "falar bobagem com gente séria",
      "banhos premium y cremes y filmes y doces",
      "uma calça jeans mais larguinha",
      "meias coloridas",
      "abandonar carrinhos digitais",
      "jejum intermitente",
      "uma unidade de panela de brigadeiro",
      "pedir desculpas",
      "tirar satisfação",
      "desligar o telefone",
      "pensar mais um pensamento",
      "navegar em sites de imobiliárias",
      "15 minutos de esteira no pau",
      "um café de 22 reais",
      "forró na pontinha do pé",
      "videochamadas",
      "decisões evidentemente erradas",
      "se apaixonar."
    ]
  },
  {
    titulo: "coisas que não são o que são:",
    itens: [
      "alguns cafés da manhã pós noites deliciosamente mal dormidas",
      "as jaquetas de couro deste feed",
      "“bora lá”",
      "…sim",
      "NÃO!",
      "chocolates em geral",
      "~pão de queijo fora de mg",
      "quando no momento do passe o zagueiro tá pra trás do atacante",
      "mensagens sem resposta",
      "selfies",
      "contas bancárias",
      "gosto de coentro",
      "choros — especialmente os de raiva",
      "sair pra fumar um cigarro",
      "eu mesma",
      "vocês também",
      "mapas astrais",
      "laudos médicos",
      "pontos finais;",
      "a maioria dos conselhos",
      "geléias do supermercado",
      "cinco minutinhos",
      "a fome das 22h em uma terça feira útil",
      "o que deu conta de sair da nossa boca",
      "as críticas mais ferozes",
      "os elogios: do chat gpt e dos humanos",
      "o que a gente quer."
    ]
  },
  {
    titulo: "lugares de onde eu venho:",
    itens: [
      "da América Latina",
      "da rua Califórnia",
      "da carrer de Siracusa",
      "da barriga da minha mãe",
      "da cabeça da minha mãe",
      "de uns sete bairros",
      "(mas confesso que meu carrinho de feira anda melhor em Copacabana)",
      "da disciplina irrevogável do meu pai",
      "das quase seis horas gastas elaborando a melhor dobradura para os novos panos de prato",
      "de alguma piscina cheia de cloro",
      "daquela dor tão forte que anestesia",
      "y das ligações prolongadas no viva voz",
      "dos caderninhos quase completos",
      "da companhia sem utilidade aparente",
      "do signo de gêmeos",
      "do alto da ladeira",
      "de baixo da Serra do Curral",
      "de alguns lugares que não são meus",
      "e de onde me pediram pra ficar",
      "de dentro da palma da mão de quem eu amo",
      "y do cangote de quem gosta de mim",
      "…",
      "eu sou de onde eu corro",
      "pra contar as melhores notícias."
    ]
  },
  {
    titulo: "razões para amar são paulo:",
    itens: [
      "mudar de bairro aqui é igual a mudar de cidade",
      "não sinto culpa pelas minhas ambições, sobretudo entre mulheres",
      "desde que moro aqui, meus amigos tem algo entre 23 e 61 anos",
      "posso sempre sair de saltinho fazendo tec tec tec por aí",
      "geral veio parar aqui pra tentar fazer alguma coisa",
      "z deli, almanara and le jazz",
      "tem dias que tenho certeza que vi todos os habitantes na rua e outros que encontro a mesma pessoa em 6 butecos",
      "sair durante a semana e quietar o facho no sábado",
      "tem grafica 24h",
      "ser mineira aqui é mais sexy",
      "o copan",
      "da pra fazer coisas radicais como: sair de um rolê do rom santana e ir andando pra um show da esperanza spalding",
      "as relações são mais intencionais quando um uber custa 47 reais",
      "fitz, penicilin y bitter giuseppe são deleites que eu não sabia que existia",
      "minhas roupas não fazem tanto sentido em outro lugar",
      "não precisa ter bom humor de manhã, mas se quiser pode",
      "ninguém conhece ninguém",
      "parque villa-lobos",
      "as janelas de higienópolis",
      "agora posso reclamar, com propriedade, da vida que eu escolhi pra mim. o que não é o melhor dos mundos, mas é preferível ao platonismo de ficar no mesmo lugar."
    ]
  },
  {
    titulo: "coisinhas para fazer em bellory hills:",
    itens: [
      "sentar na varandinha do pirex na galeria são vicente",
      "drinkinho no palito que fica ao lado",
      "pizza da vizu na savassi",
      "pão de queijo com pernil do café palhares no mercado central",
      "ler um livrinho no oop café",
      "se empanturrar de quitandas no copa cozinha",
      "a caipirinha de limão capeta do florestal",
      "cervejinha y música boa no juramento 202",
      "ver algum show massa na autêntica",
      "comer qualquer coisa da casa bonomi",
      "sentar naquela pracinha e ficar indeciso entre pérola da cidade, forno da saudade e TLTP",
      "perceber que essa è uma dúvida besta e sentar um pouquinho em cada lugar",
      "#biscoitodequeijodoelisacafe",
      "projetar uma vida belo-horizontina pelos corredores do verdemar",
      "não perder uma pistinha do alta fidelidade por nada",
      "e depois amassar o pf do chop da fábrica as 3 da manhã",
      "sentar no meio fio do bar do orlando com um copo lagoinha numa mão e um pastel de angu na outra",
      "o ccbb mais bonito é o de beagá, tá?",
      "e atenção:",
      "nesses lugares, é imprescindível se demorar."
    ]
  },
  {
    titulo: "coisas para fazer em um apartamento vazio:",
    itens: [
      "cantar e curtir o eco",
      "dançar e aproveitar o chão",
      "chorar pra preencher o espaço",
      "pensar do que a gente precisa mesmo",
      "selfies",
      "pensar mais um pouco",
      "se arrepender",
      "tomar coragem",
      "tomar vinho sentada no chão",
      "deixar um pouco de si",
      "olhar da janela pela última vez",
      "saber que è a última vez",
      "transferir a titularidade do gàs",
      "agradecer as quatro paredes",
      "e o teto também",
      "lembrar de quem era antes",
      "entender o agora",
      "espremer a memória",
      "não bater o dedinho na quina",
      "despedir do pessoal da portaria"
    ]
  },
  {
    titulo: "lista de materiais para um recomeço:",
    itens: [
      "uma caixa com doze lápis de cor",
      "tesoura sem ponta",
      "corte de cabelo",
      "término de namoro",
      "tesoura com ponta",
      "eu digo durepox, meu pai diria araldite",
      "googleflights.com",
      "manoel de barros",
      "lápis 2b com borracha na ponta",
      "o cabelo molhado y penteado pra trás",
      "um pacote de ganchos 3M",
      "escova de dentes",
      "1,5l de água mineral com gás",
      "coca-cola normal",
      "um livro facinho",
      "uma surra cinematográfica aka um filme arrebatador",
      "arrependimentos (mais de um)",
      "um mapa de volta suficientemente confuso",
      "um bloco para anotações inúteis",
      "um retrovisor com pontos estrategicamente cegos",
      "pouquíssima fofoca",
      "um tantão de superlativos",
      "e a vontade de saber."
    ]
  },
  {
    titulo: "coisas que ficam pro final:",
    itens: [
      "o beijo",
      "o melhor arquivo que deu pra chegar",
      "a dúvida infinita",
      "e se?",
      "o que só a gente faz pela gente",
      "a ausência de cabimento",
      "a surpresa",
      "a certeza",
      "o reveillon",
      "a calma",
      "a furiosa conformação",
      "o gloss",
      "a louça",
      "a digestão",
      "os sapatos",
      "a intimidade",
      "y a chegada da timidez",
      "o sono",
      "y o despertar."
    ]
  },
  {
    titulo: "coisas para dar algum nome:",
    itens: [
      "o espaço entre o ouvir e o deixar que falem.",
      "a proporção perfeita da introspecção e uma risada fora de lugar.",
      "à minha viciosa relação com o vizinho do prédio da frente: quarenta e poucos anos, provavelmente arquiteto, horários flexíveis e uma escrivaninha exatamente na mesma altura da minha.",
      "uma saudade tão imensa quanto transparente, que ocupa tudo mas não paralisa.",
      "tudo que ainda dá pra fazer;",
      "ou quando “já deu”.",
      "a estratégia de enrolar pra terminar um livro porque eu não quero que ele acabe.",
      "cheiros tristes.",
      "o que eu sinto na minha gengiva quando percebo que tô apaixonada.",
      "cumplicidade, só que muita.",
      "o espaço (de tempo) entre duas bocas.",
      "o que eu quero pra mim.",
      "o jeito que a gente dá de bordar uma vida na outra.",
      "a sensação de perfeito encaixe. sorte ou atenção?",
      "o gosto de uma primeira mordida.",
      "a dificuldade de desatar alguns nós.",
      "(…)",
      "a vontade de nomear as coisas."
    ]
  },
  {
    titulo: "motivos pra dar razão a algum astro:",
    itens: [
      "o embarque já começou e estou a 22 portões de distância do voo",
      "“você me mandou mensagem no dia seguinte que eu terminei”",
      "minhas unhas roídas",
      "o jeito que a gente corre atrás das coisas",
      "a falta de sono",
      "o excesso de coragem (isso existe?)",
      "ações impensadas",
      "planos meticulosos",
      "“gioblastoma multiforme grau 4”",
      "“eu sei lá”",
      "a geração que a gente nasce",
      "de onde a gente vem (?)",
      "a cidade que a gente morre",
      "as marés",
      "e as peles douradas",
      "os meus pensamentos último minuto",
      "e o resto da vida."
    ]
  },
  {
    titulo: "momentos bons para dizer olá:",
    itens: [
      "enquanto não houver necessidade",
      "quando o cabelo tá molhado e penteado para trás",
      "na hora de chegar",
      "no dia que deu pra dormir um pouco mais",
      "alguns anos depois do primeiro encontro",
      "segundos depois que os olhares se cruzaram",
      "quando a roupa tá combinando",
      "uma música boa começou a tocar",
      "o som já parou",
      "de repente",
      "se parece que já entendemos tudo",
      "na fila do banheiro",
      "quando parece caber",
      "se o coração fala que sim",
      "ou a boca tem algo a dizer",
      "quando já faz tempo que o novo não vem",
      "enquanto for preciso"
    ]
  },
  {
    titulo: "horas boas pra dizer tchau:",
    itens: [
      "quando tá barulhento demais",
      "a garganta já não imita a ponta dos dedos",
      "as unhas já não moram muito tempo pela mão",
      "quando o tempo demora a passar",
      "o dia tá pra nascer",
      "a carona é boa",
      "não tem cabimento",
      "dias de chuva no rio de janeiro",
      "o carisma já foi pro c4r@(€0",
      "se falta luz",
      "acenderam a luz",
      "o tempo resolveu virar e vc está de cropped",
      "o pessoal já tá indo embora",
      "se não parece ter fim",
      "no último metro antes da sala de embarque",
      "quando a vontade mandar"
    ]
  },
  {
    titulo: "coisas que eu já entendi:",
    itens: [
      "conversar com os outros é ensaiar para uma vida mais bonita.",
      "tenho alergia a conservadorismo.",
      "amo tradições.",
      "acho que odeio surpresas.",
      "meu brilho some quando alguém não entende figuras de linguagem.",
      "ainda tenho que resolver essa historia de ficar roendo unha.",
      "o brasil é a coisa mais foda de todas as coisas.",
      "amor é um verbo que se dá melhor no gerúndio.",
      "fazer também.",
      "não da pra dar carona a pé.",
      "suco de uva me da alguma indigestão.",
      "ressuscitar uma planta é massa demais.",
      "vinho é a melhor droga.",
      "trocar a roupa de cama resolve quase tudo.",
      "memória é uma coisa muito curta e muito ampla.",
      "registrar é importante."
    ]
  },
  {
    titulo: "a única maneira de fazer certas coisas:",
    itens: [
      "pedir o maior tamanho de pizza disponível",
      "esquentar essa mesma pizza na frigideira para o café da manhã",
      "banco do carona = DJ",
      "pegar o assento do corredor",
      "meia, meia, tênis, tênis",
      "tirar a roupa da rua pra sentar na cama (óbvio)",
      "coca é zero",
      "luz é quente",
      "grifar livros com um lápis da cor da capa",
      "abrir o computador pra comprar passagem",
      "arrumar o cabelo antes pra passar menos maquiagem",
      "esperar todos saírem do elevador pra entrar",
      "papel higiênico é franja, não mullet.",
      "abaixar o rádio pra estacionar melhor",
      "conversar comigo no mesmo tom que eu falaria com a minha melhor amiga"
    ]
  },
  {
    titulo: "um dia a gente é jovem e no outro:",
    itens: [
      "a ressaca parece dengue",
      "vemos nossos pais pelo espelho",
      "falamos da nossa época",
      "deixamos de entender memes",
      "assumimos o nosso cabelo",
      "a preguiça vence a opinião",
      "reclama do preço do azeite",
      "o ben do rubel é adolescente",
      "sono >>>>>",
      "rimos de nós mesmos",
      "deixamos de entender tudo",
      "damos tempo pro tempo",
      "esquece o nome do povo",
      "tem medo dos inícios",
      "adia os finais",
      "entende quem compra pacote de viagem pronto",
      "pilates é uma boa opção",
      "tem um hidratante pra região dos olhos",
      "vinagre e bicarbonato resolvem tudo",
      "deixa pra lá"
    ]
  },
  {
    titulo: "coisas simplesmente chics demais",
    itens: [
      "falar línguas",
      "esquecer que o celular existe",
      "chás de erva fresquinha",
      "ter avós",
      "chegar no horário",
      "pensar antes de falar",
      "ler antes de pensar",
      "saber as linhas do metrô",
      "só uma tacinha",
      "água naturalmente gaseificada",
      "dormir cedo no sábado",
      "dormir sem despertador",
      "luz do outono",
      "meias estações",
      "as bolsas da minha mãe",
      "ouvir o que temos por dentro",
      "& botar pra fora com doçura"
    ]
  },
  {
    titulo: "formas que eu sinto a sua presença:",
    itens: [
      "escolhendo uma roupa mais larguinha",
      "lavando a louça like a pro (agr tenho uma máquina)",
      "quando toca queen",
      "trocando a roupa de cama com capricho",
      "bebendo destilados like a pro",
      "quando tô mal pra car~£|¥",
      "quando consigo falar um pouco menos",
      "quando o que eu tô cozinhando da errado",
      "quando tô pura euforia",
      "agr vai ter essa história de pegar uma gripe e ir pro HOSPITAL? achei exagerado.",
      "me lembro de vc quando compro 25x a quantidade de aviamentos necessárias.",
      "mas isso não são critérios: você não se limita ao trivial.",
      "me lembro de você olhando no espelho. cada vez menos por que dizem ser assim, cada vez mais por que somos assim."
    ]
  },
  {
    titulo: "coisas chics que eu te desejo:",
    itens: [
      "alinhamentos espontâneos",
      "falar borracha até dar cãibra nas bochechas",
      "vinhos iphones laranjas",
      "que você acorde achando que seu cabelo tá massa",
      "cheiros felizes",
      "literatura de curitiba, camisas de linho e anéis de prata",
      "janelas semi abertas",
      "minha presença hihihi",
      "fontes variadas de vitamina D",
      "que a torrada queime menos vezes",
      "e o seu mundo melhorando."
    ]
  }
];
